In [2]:
from torch.nn.utils.rnn import pack_sequence, pad_packed_sequence
import torch

a = torch.tensor([4,5,6])
b = torch.tensor([2,3])
c = torch.tensor([1])
input_data = ([a,b,c])
print(input_data)
# [tensor([1]), tensor([2, 3]), tensor([4, 5, 6])]
packed = pack_sequence(input_data, enforce_sorted=True) # enforce_sortedはデフォルトがTrue
print(packed)
# PackedSequence(data=tensor([4, 2, 1, 5, 3, 6]), 
# batch_sizes=tensor([3, 2, 1]), 
# sorted_indices=None, unsorted_indices=None)
padded, x = pad_packed_sequence(packed, batch_first=True, 
                                padding_value=0, total_length=None)
print(padded)
print(x)

[tensor([4, 5, 6]), tensor([2, 3]), tensor([1])]
PackedSequence(data=tensor([4, 2, 1, 5, 3, 6]), batch_sizes=tensor([3, 2, 1]), sorted_indices=None, unsorted_indices=None)
tensor([[4, 5, 6],
        [2, 3, 0],
        [1, 0, 0]])
tensor([3, 2, 1])


In [4]:
torch.zeros(3, 2, dtype=torch.long)

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [7]:
a = torch.tensor([8,3,6])
b = torch.tensor([2,4,1])
c = torch.tensor([2,0,1])

c, idx = c.sort(descending=True)
print(c, idx)
a = a[idx]
b = b[idx]
print(a)
print(b)

tensor([2, 1, 0]) tensor([0, 2, 1])
tensor([8, 6, 3])
tensor([2, 1, 4])


In [10]:
a = torch.tensor([1, 1, 1])
b = torch.tensor([0, 0, 0])
c = torch.cat([a, b], dim=0)
c

tensor([1, 1, 1, 0, 0, 0])

In [16]:
a = torch.tensor([1, 2, 3])

len(a)

3

In [3]:
import torch

a = [0] * 3
a = torch.tensor(a)

if a.any():
    print('a')